### ISSUE TITLE
PermissionError when running hf_interactive notebook

### ISSUE THREAD

**Issue by mamurak** [project-codeflare/codeflare-sdk#193]
When running the `hf_interactive` notebook in `codeflare-examples/interactive` folder, the execution of the training function on the Ray cluster fails with a PermissionError indicating a lack of write access.

Executed cell:
```
#call the above cell as a remote ray function
ray.get(train_fn.remote())
```
Error message:
```
(train_fn pid=306) There was a problem when trying to write in your cache folder (/home/ray/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.

---------------------------------------------------------------------------
RayTaskError(PermissionError)             Traceback (most recent call last)
Cell In [26], line 2
      1 #call the above cell as a remote ray function
----> 2 ray.get(train_fn.remote())

File /opt/app-root/lib64/python3.8/site-packages/ray/_private/client_mode_hook.py:104, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    100 if client_mode_should_convert(auto_init=auto_init):
    101     # Legacy code
    102     # we only convert init function if RAY_CLIENT_MODE=1
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104         return getattr(ray, func.__name__)(*args, **kwargs)
    105 return func(*args, **kwargs)

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/api.py:42, in _ClientAPI.get(self, vals, timeout)
     35 def get(self, vals, *, timeout=None):
     36     """get is the hook stub passed on to replace `ray.get`
     37 
     38     Args:
     39         vals: [Client]ObjectRef or list of these refs to retrieve.
     40         timeout: Optional timeout in milliseconds
     41     """
---> 42     return self.worker.get(vals, timeout=timeout)

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/worker.py:434, in Worker.get(self, vals, timeout)
    432     op_timeout = max_blocking_operation_time
    433 try:
--> 434     res = self._get(to_get, op_timeout)
    435     break
    436 except GetTimeoutError:

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/worker.py:462, in Worker._get(self, ref, timeout)
    460         logger.exception("Failed to deserialize {}".format(chunk.error))
    461         raise
--> 462     raise err
    463 if chunk.total_size > OBJECT_TRANSFER_WARNING_SIZE and log_once(
    464     "client_object_transfer_size_warning"
    465 ):
    466     size_gb = chunk.total_size / 2 ** 30

RayTaskError(PermissionError): ray::train_fn() (pid=306, ip=10.130.2.26)
  File "/tmp/ipykernel_1280/2385736567.py", line 11, in train_fn
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/huggingface/__init__.py", line 3, in <module>
    from ray.train.huggingface.huggingface_trainer import (
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/train/huggingface/huggingface_trainer.py", line 69, in <module>
    datasets.load.init_dynamic_modules(), "__init__.py"
  File "/tmp/ray/session_2023-07-05_07-29-03_609674_8/runtime_resources/pip/4a36d7bd0bbff8fccea52f9c0d942dd63707933f/virtualenv/lib/python3.8/site-packages/datasets/load.py", line 102, in init_dynamic_modules
    hf_modules_cache = init_hf_modules(hf_modules_cache)
  File "/tmp/ray/session_2023-07-05_07-29-03_609674_8/runtime_resources/pip/4a36d7bd0bbff8fccea52f9c0d942dd63707933f/virtualenv/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 56, in init_hf_modules
    os.makedirs(hf_modules_cache, exist_ok=True)
  File "/home/ray/anaconda3/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ray/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/ray/.cache/huggingface'
```

Setup:
- OCP 4.10
- RHODS 1.28.1
- CodeFlare Operator 0.0.4
- Kuberay operator 0.5.0

**Comment by mamurak** [comment]
Adding `namespace='default'` argument to the `ClusterConfiguration` during cluster initialization fixes the permission error. The training script is running and failing towards the end with an ImportError:

```
                                                                   
(_get_metadata pid=1040) 2023-07-05 08:13:57,036	INFO worker.py:763 -- Task failed with retryable exception: TaskID(3af70994bb3459ffffffffffffffffffffffffff01000000).
(_get_metadata pid=1040) Traceback (most recent call last):
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 859, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 863, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1353, in _get_metadata
(_get_metadata pid=1040)     return BlockAccessor.for_block(table).get_metadata(
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/block.py", line 378, in for_block
(_get_metadata pid=1040)     _check_pyarrow_version()
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/util.py", line 78, in _check_pyarrow_version
(_get_metadata pid=1040)     raise ImportError(
(_get_metadata pid=1040) ImportError: Datasets requires pyarrow >= 6.0.1, < 7.0.0, but 12.0.1 is installed. Reinstall with `pip install -U "pyarrow<7.0.0"`. If you want to disable this pyarrow version check, set the environment variable RAY_DISABLE_PYARROW_VERSION_CHECK=1.
(_get_metadata pid=1040) 2023-07-05 08:13:57,541	INFO worker.py:763 -- Task failed with retryable exception: TaskID(3af70994bb3459ffffffffffffffffffffffffff01000000).
(_get_metadata pid=1040) Traceback (most recent call last):
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 859, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 863, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1353, in _get_metadata
(_get_metadata pid=1040)     return BlockAccessor.for_block(table).get_metadata(
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/block.py", line 378, in for_block
(_get_metadata pid=1040)     _check_pyarrow_version()
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/util.py", line 78, in _check_pyarrow_version
(_get_metadata pid=1040)     raise ImportError(
(_get_metadata pid=1040) ImportError: Datasets requires pyarrow >= 6.0.1, < 7.0.0, but 12.0.1 is installed. Reinstall with `pip install -U "pyarrow<7.0.0"`. If you want to disable this pyarrow version check, set the environment variable RAY_DISABLE_PYARROW_VERSION_CHECK=1.
(_get_metadata pid=1040) 2023-07-05 08:13:58,542	INFO worker.py:763 -- Task failed with retryable exception: TaskID(3af70994bb3459ffffffffffffffffffffffffff01000000).
(_get_metadata pid=1040) Traceback (most recent call last):
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 859, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 863, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1353, in _get_metadata
(_get_metadata pid=1040)     return BlockAccessor.for_block(table).get_metadata(
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/block.py", line 378, in for_block
(_get_metadata pid=1040)     _check_pyarrow_version()
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/util.py", line 78, in _check_pyarrow_version
(_get_metadata pid=1040)     raise ImportError(
(_get_metadata pid=1040) ImportError: Datasets requires pyarrow >= 6.0.1, < 7.0.0, but 12.0.1 is installed. Reinstall with `pip install -U "pyarrow<7.0.0"`. If you want to disable this pyarrow version check, set the environment variable RAY_DISABLE_PYARROW_VERSION_CHECK=1.
(_get_metadata pid=1040) 2023-07-05 08:13:59,543	INFO worker.py:763 -- Task failed with retryable exception: TaskID(3af70994bb3459ffffffffffffffffffffffffff01000000).
(_get_metadata pid=1040) Traceback (most recent call last):
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 859, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "python/ray/_raylet.pyx", line 863, in ray._raylet.execute_task
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1353, in _get_metadata
(_get_metadata pid=1040)     return BlockAccessor.for_block(table).get_metadata(
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/block.py", line 378, in for_block
(_get_metadata pid=1040)     _check_pyarrow_version()
(_get_metadata pid=1040)   File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/util.py", line 78, in _check_pyarrow_version
(_get_metadata pid=1040)     raise ImportError(
(_get_metadata pid=1040) ImportError: Datasets requires pyarrow >= 6.0.1, < 7.0.0, but 12.0.1 is installed. Reinstall with `pip install -U "pyarrow<7.0.0"`. If you want to disable this pyarrow version check, set the environment variable RAY_DISABLE_PYARROW_VERSION_CHECK=1.

---------------------------------------------------------------------------
RayTaskError(ImportError)                 Traceback (most recent call last)
Cell In [13], line 2
      1 #call the above cell as a remote ray function
----> 2 ray.get(train_fn.remote())

File /opt/app-root/lib64/python3.8/site-packages/ray/_private/client_mode_hook.py:104, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    100 if client_mode_should_convert(auto_init=auto_init):
    101     # Legacy code
    102     # we only convert init function if RAY_CLIENT_MODE=1
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104         return getattr(ray, func.__name__)(*args, **kwargs)
    105 return func(*args, **kwargs)

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/api.py:42, in _ClientAPI.get(self, vals, timeout)
     35 def get(self, vals, *, timeout=None):
     36     """get is the hook stub passed on to replace `ray.get`
     37 
     38     Args:
     39         vals: [Client]ObjectRef or list of these refs to retrieve.
     40         timeout: Optional timeout in milliseconds
     41     """
---> 42     return self.worker.get(vals, timeout=timeout)

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/worker.py:434, in Worker.get(self, vals, timeout)
    432     op_timeout = max_blocking_operation_time
    433 try:
--> 434     res = self._get(to_get, op_timeout)
    435     break
    436 except GetTimeoutError:

File /opt/app-root/lib64/python3.8/site-packages/ray/util/client/worker.py:462, in Worker._get(self, ref, timeout)
    460         logger.exception("Failed to deserialize {}".format(chunk.error))
    461         raise
--> 462     raise err
    463 if chunk.total_size > OBJECT_TRANSFER_WARNING_SIZE and log_once(
    464     "client_object_transfer_size_warning"
    465 ):
    466     size_gb = chunk.total_size / 2 ** 30

RayTaskError(ImportError): ray::train_fn() (pid=306, ip=10.130.2.29)
  File "/tmp/ipykernel_2385/2385736567.py", line 27, in train_fn
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1321, in from_huggingface
    return convert(dataset)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1316, in convert
    return from_arrow(ds.data.table)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1239, in from_arrow
    return from_arrow_refs([ray.put(t) for t in tables])
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1262, in from_arrow_refs
    metadata = ray.get([get_metadata.remote(t) for t in tables])
ray.exceptions.RayTaskError(ImportError): ray::_get_metadata() (pid=1040, ip=10.130.2.29)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/read_api.py", line 1353, in _get_metadata
    return BlockAccessor.for_block(table).get_metadata(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/block.py", line 378, in for_block
    _check_pyarrow_version()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/data/_internal/util.py", line 78, in _check_pyarrow_version
    raise ImportError(
ImportError: Datasets requires pyarrow >= 6.0.1, < 7.0.0, but 12.0.1 is installed. Reinstall with `pip install -U "pyarrow<7.0.0"`. If you want to disable this pyarrow version check, set the environment variable RAY_DISABLE_PYARROW_VERSION_CHECK=1.
```

**Comment by MichaelClifford** [comment]
see this issue:  https://github.com/project-codeflare/codeflare-sdk/issues/170

**Comment by mamurak** [comment]
Good call. Adding the `pyarrow` and `transformers` dependencies fixes the issue. Thanks @MichaelClifford!
