### ISSUE TITLE
Kubernetes authentication not working from inside the cluster

### ISSUE THREAD

**Issue by kpouget** [project-codeflare/codeflare-sdk#255]
I'm running a [simple code](https://github.com/openshift-psap/ci-artifacts/blob/main/testing/codeflare/sdk_user/sample/sample.py#L27) based on [this example](https://github.com/opendatahub-io/distributed-workloads/blob/main/tests/resources/mnist_ray_mini.ipynb):
```python
    from codeflare_sdk.cluster.cluster import Cluster, ClusterConfiguration

    # Create our cluster and submit appwrapper
    cluster = Cluster(ClusterConfiguration(
        namespace=namespace, name=f"{name}-user{user_idx}",
        image=image,
        min_worker=workers, max_worker=workers,
        min_cpus=cpu, max_cpus=cpu,
        min_memory=memory, max_memory=memory,
        gpu=gpu, instascale=False))

    # Bring up the cluster
    cluster.up()
```
but this last call [fails with](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift-psap_ci-artifacts/876/pull-ci-openshift-psap-ci-artifacts-main-codeflare-e2e/1684815166618734592/artifacts/e2e/test/artifacts/000__sdk_user_run_many/000__local_ci__run_multi/ci-pods_artifacts/ci-pod-0/run.log) **when deployed from the current `main` branch**:
```
Traceback (most recent call last):
  File "/opt/venv/src/codeflare-sdk/src/codeflare_sdk/cluster/cluster.py", line 120, in up
    config_check()
  File "/opt/venv/src/codeflare-sdk/src/codeflare_sdk/cluster/auth.py", line 165, in config_check
    config.load_kube_config()
  File "/opt/venv/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 813, in load_kube_config
    loader = _get_kube_config_loader(
  File "/opt/venv/lib/python3.9/site-packages/kubernetes/config/kube_config.py", line 770, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

During handling of the above exception, another exception occurred:
...
File "/mnt/logs/002__run_one/sample.py", line 37, in main
  cluster.up()
File "/opt/venv/src/codeflare-sdk/src/codeflare_sdk/cluster/cluster.py", line 132, in up
  return _kube_api_error_handling(e)
File "/opt/venv/src/codeflare-sdk/src/codeflare_sdk/utils/kube_api_helpers.py", line 32, in _kube_api_error_handling
  raise PermissionError(perm_msg)
PermissionError: Action not permitted, have you put in correct/up-to-date auth credentials?
```

This code is running inside a Pod, and relying on the in-cluster config (token from this file: `/run/secrets/kubernetes.io/serviceaccount/token`)

**Comment by kpouget** [comment]
Adding this test to  the Kubernetes authentication should address the issue:
```
    if 'KUBERNETES_PORT' in os.environ:
        # os.environ['KUBERNETES_SERVICE_HOST'] = 'kubernetes'
        config.load_incluster_config()
    else:
        config.load_kube_config()
```

**Comment by Maxusmusti** [comment]
@Bobbins228 from your slack thread earlier
