### ISSUE TITLE
Ray Cluster cannot be accessible via ClusterConfiguration for the already created Ray cluster

### ISSUE THREAD

**Issue by Srihari1192** [project-codeflare/codeflare-sdk#411]
### Describe the Bug

Ray Cluster cannot be accessible via ClusterConfiguration with cluster name and namespaces for the already created Ray cluster, prompting as Image must be specified in the ClusterConfiguration

**Error log:**

Traceback (most recent call last):180File "mnist_rayjob.py", line 11, in <module>181cluster = Cluster(ClusterConfiguration(name='mnist',namespace=namespace))182File "/opt/app-root/lib64/python3.8/site-packages/codeflare_sdk/cluster/cluster.py", line 73, in __init__183self.app_wrapper_yaml = self.create_app_wrapper()184File "/opt/app-root/lib64/python3.8/site-packages/codeflare_sdk/cluster/cluster.py", line 157, in create_app_wrapper185self.validate_image_config()186File "/opt/app-root/lib64/python3.8/site-packages/codeflare_sdk/cluster/cluster.py", line 139, in validate_image_config187raise ValueError("Image must be specified in the ClusterConfiguration")188ValueError: Image must be specified in the ClusterConfiguration 

### Steps to Reproduce the Bug

1.Create a ray cluster using codeflare sdk
2. try to access the ray cluster using ClusterConfiguration cluster = Cluster(ClusterConfiguration(name='mnist', namespace=namespace)) 
3. check whether cluster is accessible or not
Error says that Image parameter should pass for cluster accessible, for connecting existing cluster image should not be provided

### What Have You Already Tried to Debug the Issue?

Provide a clear and concise description of how you tried to debug this issue.

### Expected Behavior

Ray cluster should be able to connect with cluster name and namespace parameters
cluster = Cluster(ClusterConfiguration(name='mnist', namespace=namespace)) 

### Screenshots, Console Output, Logs, etc.
https://github.com/project-codeflare/codeflare-operator/actions/runs/6966971769/job/18958016578?pr=286

**Comment by Bobbins228** [comment]
Closing this issue as the `get_cluster` method  can be used instead of creating a new cluster configuration
